# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hwankim <hwankim@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/14 17:10:31 by hwankim           #+#    #+#              #
#    Updated: 2023/02/07 16:18:00 by hwankim          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= libft.a

CC		= cc
CFLAGS	= -Wall -Wextra -Werror

SRCS 	=		ft_atoi.c \
				ft_bzero.c \
				ft_calloc.c \
				ft_isalnum.c \
				ft_isalpha.c \
				ft_isascii.c \
				ft_isdigit.c \
				ft_isprint.c \
				ft_itoa.c \
				ft_memchr.c \
				ft_memcmp.c \
				ft_memcpy.c \
				ft_memmove.c \
				ft_memset.c \
				ft_putchar_fd.c \
				ft_putendl_fd.c \
				ft_putnbr_fd.c \
				ft_putstr_fd.c \
				ft_split.c \
				ft_strchr.c \
				ft_strdup.c \
				ft_striteri.c \
				ft_strjoin.c \
				ft_strlcat.c \
				ft_strlcpy.c \
				ft_strlen.c \
				ft_strmapi.c \
				ft_strncmp.c \
				ft_strnstr.c \
				ft_strrchr.c \
				ft_strtrim.c \
				ft_substr.c \
				ft_tolower.c \
				ft_toupper.c \
				ft_strcmp.c

SRCS_BONUS = 	ft_lstadd_back.c \
				ft_lstadd_front.c \
				ft_lstclear.c \
				ft_lstdelone.c \
				ft_lstiter.c \
				ft_lstlast.c \
				ft_lstmap.c \
				ft_lstnew.c \
				ft_lstsize.c

OBJS		= $(SRCS:.c=.o)
OBJS_BONUS 	= $(SRCS_BONUS:.c=.o)

ARCHIVE		= ar -crs
REMOVE		= rm -f

ifdef WITH_BONUS
			OBJECTS	= $(OBJS) $(OBJS_BONUS)
else
			OBJECTS	= $(OBJS)
endif

all		:	$(NAME)

%.o		:	%.c
	@$(CC) $(CFLAGS) -c -o $@ $<

$(NAME)	:	$(OBJECTS)
	@$(ARCHIVE) $(NAME) $(OBJECTS)

bonus	:
	@make WITH_BONUS=1 all

clean	:
	@$(REMOVE) $(OBJS) $(OBJS_BONUS)

fclean	:	clean
	@$(REMOVE) $(NAME)

re		:   fclean
	@make all

.PHONY	: bonus all clean fclean re